#!/usr/bin/env bash
#
# Terraforming:
# - Export existing AWS resources to Terraform style (tf, tfstate)
#
# Doc:
# - https://github.com/dtan4/terraforming
#
#
# == Vars
#
# Hub.docker.io
DOCKER_REGISTRY="${DOCKER_REGISTRY/:-''}"
DOCKER_IMAGE=quay.io/dtan4/terraforming
DOCKER_IMAGE_TAG=latest


docker run \
  --rm \
  --env="AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
  --env="AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
  --env="AWS_REGION=${AWS_REGION}" \
  ${DOCKER_REGISTRY}${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG} \
  terraforming "$@"
